fos_rest:
  zone:
    - { path: '^/api' }
  view:
    view_response_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: [ json ] }
  exception:
    enabled: true