nelmio_cors:
    defaults:
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-AUTH-TOKEN']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600